Repository nodejs/nodejs.dev, pull requests merged in 2019-04, with the labels that each got.

#215 feat: AuthorsList Component with Github Profile Photos
  src/components/article.tsx
  src/components/author-link.tsx
  src/components/author.tsx
  src/components/authors-list.tsx
  src/documentation/0001-node-introduction/index.md
  test/components/__snapshots__/article.test.tsx.snap
  test/components/__snapshots__/author-link.test.tsx.snap
  test/components/author-link.test.tsx
Labels: enhancement

#217 fix: Add tests and make markup semantic (outstanding nits from #215)
  src/components/author.tsx
  src/components/authors-list.tsx
  test/components/__snapshots__/author-link.test.tsx.snap
  test/components/__snapshots__/author.test.tsx.snap
  test/components/__snapshots__/authors-list.test.tsx.snap
  test/components/author.test.tsx
  test/components/authors-list.test.tsx
Labels: enhancement, refactor

#219 docs: Add & Sync-up Contributors
  src/documentation/0002-node-history/index.md
  src/documentation/0003-node-installation/index.md
  src/documentation/0004-node-javascript-language/index.md
  src/documentation/0005-node-difference-browser/index.md
  src/documentation/0006-v8/index.md
  src/documentation/0007-node-run-cli/index.md
  src/documentation/0008-node-terminate-program/index.md
  src/documentation/0009-node-environment-variables/index.md
  src/documentation/0010-node-hosting/index.md
  src/documentation/0011-node-repl/index.md
  src/documentation/0012-node-cli-args/index.md
  src/documentation/0013-node-output-to-cli/index.md
  src/documentation/0014-node-input-from-cli/index.md
  src/documentation/0015-node-export-module/index.md
  src/documentation/0016-npm/index.md
  src/documentation/0017-where-npm-install-packages/index.md
  src/documentation/0018-how-to-use-npm-package/index.md
  src/documentation/0019-package-json/index.md
  src/documentation/0020-package-lock-json/index.md
  src/documentation/0021-npm-know-version-installed/index.md
  src/documentation/0022-npm-install-previous-package-version/index.md
  src/documentation/0023-update-npm-dependencies/index.md
  src/documentation/0024-npm-semantic-versioning/index.md
  src/documentation/0025-npm-uninstall-packages/index.md
  src/documentation/0026-npm-packages-local-global/index.md
  src/documentation/0027-npm-dependencies-devdependencies/index.md
  src/documentation/0028-npx/index.md
  src/documentation/0029-node-event-loop/index.md
  src/documentation/0030-node-process-nexttick/index.md
  src/documentation/0031-node-setimmediate/index.md
  src/documentation/0032-javascript-timers/index.md
  src/documentation/0033-javascript-callbacks/index.md
  src/documentation/0034-javascript-promises/index.md
  src/documentation/0035-javascript-async-await/index.md
  src/documentation/0036-node-event-emitter/index.md
  src/documentation/0037-node-http-server/index.md
  src/documentation/0038-node-make-http-requests/index.md
  src/documentation/0039-node-http-post/index.md
  src/documentation/0040a-node-request-data/index.md
  src/documentation/0040b-node-file-descriptors/index.md
  src/documentation/0041-node-file-stats/index.md
  src/documentation/0042-node-file-paths/index.md
  src/documentation/0043-node-reading-files/index.md
  src/documentation/0044-node-writing-files/index.md
  src/documentation/0045-node-folders/index.md
  src/documentation/0046-node-module-fs/index.md
  src/documentation/0047-node-module-path/index.md
  src/documentation/0048-node-module-os/index.md
  src/documentation/0049-node-module-events/index.md
  src/documentation/0050-node-module-http/index.md
  src/documentation/0051-node-buffers/index.md
  src/documentation/0052-nodejs-streams/index.md
  src/documentation/0053-node-difference-dev-prod/index.md
  src/documentation/0054-node-exceptions/index.md
  src/documentation/0055-node-inspect-object/index.md
Labels: docs

#220 feat: Edit links with SVG Icons & Consistent styles for Pagination/Contributors
  src/components/authors-list.tsx
  src/components/edit-link.tsx
  src/components/pagination.tsx
  test/components/__snapshots__/authors-list.test.tsx.snap
  test/components/__snapshots__/edit-link.test.tsx.snap
  test/components/__snapshots__/pagination.test.tsx.snap
Labels: enhancement

#221 style: Brand color hover on links
  package.json
  src/components/author.tsx
  src/components/authors-list.tsx
  src/components/layout.css
  test/components/__snapshots__/author.test.tsx.snap
  test/components/__snapshots__/authors-list.test.tsx.snap
Labels: enhancement

#230 Fix npm scripts
  package.json
Labels: enhancement, refactor
