Repository nodejs/nodejs.dev, pull requests merged in 2019-02, with the labels that each got.

#58 feat: Improve slug generation.
  gatsby-node.js
  src/pages/learn.tsx
  src/util/createSlug.js
Labels: enhancement

#39 fix: Edit this page on Github link added on every doc page.
  src/pages/learn.tsx
Labels: enhancement

#61 refactor: Split components into smaller pieces.
  src/components/article.tsx
  src/components/edit-link.tsx
  src/components/hero.tsx
  src/components/navigation-item.tsx
  src/components/navigation-section.tsx
  src/components/navigation.tsx
  src/components/pagination.tsx
  src/documentation/0001-node-introduction/index.md
  src/documentation/0002-node-history/index.md
  src/documentation/0003-node-installation/index.md
  src/documentation/0004-node-javascript-language/index.md
  src/documentation/0005-node-difference-browser/index.md
  src/pages/learn.tsx
  src/types/index.ts
  src/util/findActive.ts
Labels: refactor

#131 fix: Homepage SEO Title & Description.
  src/pages/learn.tsx
Labels: bug
