Repository nodejs/nodejs.dev, pull requests merged in 2022-10, with the labels that each got.

#2845 Test: Add more tests for SideNavBar component
  src/components/SideNavBar/__tests__/index.test.tsx
Labels: hacktoberfest-accepted

#2843 chore(dependencies): updated dependencies and removed some overrides
  package-lock.json
  package.json
  src/__fixtures__/hooks.tsx
  src/components/Codebox/index.module.scss
  src/components/Codebox/index.tsx
  src/components/DataTag/index.module.scss
  src/components/Header/index.tsx
  src/components/RandomContributor/index.tsx
  src/components/SearchBar/index.module.scss
  src/components/SearchBar/index.tsx
  src/hooks/index.tsx
  src/hooks/useNvmVersion.tsx
  src/hooks/useSearchResults.ts
  src/styles/templates/api.module.scss
  src/types/index.ts
Labels: enhancement, docs, dependencies

#2810 Fix: footer a11y
  src/components/Footer/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Footer/index.tsx
  src/components/Layout/__tests__/__snapshots__/page.test.tsx.snap
  src/pages/about/__tests__/__snapshots__/resources.test.tsx.snap
  src/pages/download/__tests__/__snapshots__/index.test.tsx.snap
  src/pages/download/__tests__/__snapshots__/package-manager.test.tsx.snap
  src/templates/__tests__/__snapshots__/learn.test.tsx.snap
  src/templates/__tests__/__snapshots__/post.test.tsx.snap
Labels: a11y

#2851 Update 404 redirects
  firebase.json
  redirects.js
Labels: hacktoberfest-accepted

#2857 test(util): add test for parseApiDocsVersion in util
  src/util/__tests__/parseApiDocsVersion.test.ts
Labels: hacktoberfest-accepted

#2854 feat: add sync api github action
  .github/workflows/sync-api.yml
Labels: enhancement, docs, Infrastructure, hacktoberfest-accepted

#2866 Cannot scroll on the "About" pages sidebar
  src/components/SideNavBar/__tests__/index.test.tsx
  src/components/SideNavBar/index.tsx
Labels: enhancement, hacktoberfest-accepted

#2867 Test: add test for SectionTitle component
  src/components/SectionTitle/__tests__/SectionTitle.test.tsx
  src/components/SectionTitle/__tests__/__snapshots__/SectionTitle.test.tsx.snap
Labels: enhancement, hacktoberfest-accepted

#2864 Fix: secondary nav accessibility
  src/components/NavigationSection/__tests__/__snapshots__/index.test.tsx.snap
  src/components/NavigationSection/index.module.scss
  src/components/NavigationSection/index.tsx
  src/containers/Navigation/__tests__/__snapshots__/navigation.test.tsx.snap
  src/containers/Navigation/index.module.scss
  src/containers/Navigation/index.tsx
  src/templates/__tests__/__snapshots__/learn.test.tsx.snap
Labels: enhancement, hacktoberfest-accepted, a11y

#2858 Test: add test for DataTag component
  src/components/DataTag/__tests__/__snapshots__/index.test.tsx.snap
  src/components/DataTag/__tests__/index.test.tsx
Labels: hacktoberfest-accepted

#2884 chore(og:image): update og:image
  src/config.json
  static/static/images/og-image.png
Labels: hacktoberfest-accepted

#2850 Test: Add unit tests for DarkModeToggle component
  firebase.json
  src/components/DarkModeToggle/__tests__/__snapshots__/index.test.tsx.snap
  src/components/DarkModeToggle/__tests__/index.test.tsx
Labels: enhancement, hacktoberfest-accepted

#2878 feat(useClipboardCopy): copy text hook
  src/components/Codebox/index.tsx
  src/components/ShellBox/index.tsx
  src/components/SideNavBar/__tests__/index.test.tsx
  src/util/__tests__/copyTextToClipboard.test.ts
  src/util/copyTextToClipboard.ts
Labels: hacktoberfest-accepted

#2888 fix: add aria-pressed to dark mode toggle
  src/components/DarkModeToggle/__tests__/__snapshots__/index.test.tsx.snap
  src/components/DarkModeToggle/index.tsx
  src/components/Header/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Layout/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Layout/__tests__/__snapshots__/page.test.tsx.snap
  src/pages/about/__tests__/__snapshots__/resources.test.tsx.snap
  src/pages/download/__tests__/__snapshots__/index.test.tsx.snap
  src/pages/download/__tests__/__snapshots__/package-manager.test.tsx.snap
  src/templates/__tests__/__snapshots__/learn.test.tsx.snap
  src/templates/__tests__/__snapshots__/post.test.tsx.snap
Labels: hacktoberfest-accepted

#2906 Update current team
  README.md
Labels: fast track

#2913 chore(content): updated content fixing a few issues
  content/get-involved/index.en.md
  content/get-involved/index.fr.md
  content/learn/asynchronous-work/blocking-vs-non-blocking.en.md
  content/learn/asynchronous-work/javascript-callbacks.en.md
  content/learn/asynchronous-work/javascript-timers/index.en.md
  content/learn/asynchronous-work/node-control-flow.en.md
  content/learn/asynchronous-work/node-event-emitter.en.md
  content/learn/asynchronous-work/node-process-nexttick.en.md
  content/learn/asynchronous-work/node-setimmediate.en.md
  content/learn/getting-started/node-difference-browser.en.md
  content/learn/getting-started/node-es6.en.md
  content/learn/getting-started/node-installation.en.md
  content/learn/getting-started/node-javascript-language.en.md
  content/learn/getting-started/node-with-typescript.en.md
  content/learn/getting-started/node-with-web-assembly.en.md
  content/learn/manipulating-files/node-file-stats.en.md
  content/learn/manipulating-files/node-folders.en.md
  content/learn/manipulating-files/node-writing-files.en.md
Labels: docs, fast track

#2922 test(DownloadableItem): add test
  src/components/DownloadComponents/DownloadAdditional/DownloadableItem/__tests__/__snapshots__/index.test.tsx.snap
  src/components/DownloadComponents/DownloadAdditional/DownloadableItem/__tests__/index.test.tsx
Labels: hacktoberfest-accepted

#2920 test(replaceDataTag): add test
  src/util/__tests__/replaceDataTag.test.ts
Labels: hacktoberfest-accepted

#2917 test(BlockQuote): add test
  src/components/ArticleComponents/BlockQuote/__tests__/__snapshots__/index.test.tsx.snap
  src/components/ArticleComponents/BlockQuote/__tests__/index.test.tsx
Labels: hacktoberfest-accepted

#2915 test(alert): add test
  src/components/ArticleComponents/Alert/__tests__/__snapshots__/index.test.tsx.snap
  src/components/ArticleComponents/Alert/__tests__/index.test.tsx
Labels: enhancement, hacktoberfest-accepted

#2919 test(getUpcomingReleases): add test
  src/util/__tests__/getUpcomingReleases.test.ts
Labels: hacktoberfest-accepted

#2927 fix: lang selector keyboard accessibility
  src/components/CommonComponents/Dropdown/index.tsx
  src/components/CommonComponents/LanguageSelector/__tests__/__snapshots__/LanguageSelector.test.tsx.snap
  src/components/CommonComponents/LanguageSelector/index.tsx
  src/layouts/__tests__/__snapshots__/index.test.tsx.snap
  src/layouts/__tests__/__snapshots__/page.test.tsx.snap
  src/pages/about/__tests__/__snapshots__/resources.test.tsx.snap
  src/pages/download/__tests__/__snapshots__/index.test.tsx.snap
  src/pages/download/__tests__/__snapshots__/package-manager.test.tsx.snap
  src/sections/Header/__tests__/__snapshots__/index.test.tsx.snap
  src/templates/__tests__/__snapshots__/learn.test.tsx.snap
  src/templates/__tests__/__snapshots__/post.test.tsx.snap
Labels: hacktoberfest-accepted, a11y

#2928 Fix: download toggle button accessibility/translation support
  src/components/DownloadComponents/DownloadAdditional/__tests__/__snapshots__/index.test.tsx.snap
  src/components/DownloadComponents/DownloadToggle/__tests__/__snapshots__/index.test.tsx.snap
  src/components/DownloadComponents/DownloadToggle/index.tsx
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/zh-cn.json
  src/pages/download/__tests__/__snapshots__/index.test.tsx.snap
Labels: hacktoberfest-accepted

#2911 feat(api): add link to json docs
  apiUrls.js
  src/components/ApiComponents/Components/JsonLink/index.module.scss
  src/components/ApiComponents/Components/JsonLink/index.tsx
  src/components/ApiComponents/Components/__tests__/__snapshots__/index.test.tsx.snap
  src/components/ApiComponents/Components/__tests__/index.test.tsx
  src/components/ApiComponents/Components/index.tsx
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/i18n/locales/fr.json
  src/i18n/locales/zh-cn.json
  src/sections/Article/__tests__/index.test.tsx
  src/sections/Article/index.tsx
  src/templates/api.tsx
  util-node/__tests__/__snapshots__/getNodeReleasesData.test.ts.snap
Labels: hacktoberfest-accepted

#2942 fix(NavigationSection): Invert carets direction when a section is open/closed
  src/navigations/learn.tsx
  src/templates/__tests__/__snapshots__/learn.test.tsx.snap
Labels: hacktoberfest-accepted

#2937 dowload button focus state fix
  src/components/CommonComponents/Hero/index.module.scss
Labels: hacktoberfest-accepted

#2952 fix(SearchBar): SearchBar close while navigating tab key
  src/components/CommonComponents/SearchBar/index.tsx
Labels: hacktoberfest-accepted

#2951 Feature/components/pagination
  gatsby-node.js
  src/components/BlogComponents/Pagination/PaginationNextPage.tsx
  src/components/BlogComponents/Pagination/PaginationPage.tsx
  src/components/BlogComponents/Pagination/PaginationPreviousPage.tsx
  src/components/BlogComponents/Pagination/__tests__/Pagination.test.tsx
  src/components/BlogComponents/Pagination/__tests__/__snapshots__/Pagination.test.tsx.snap
  src/components/BlogComponents/Pagination/index.module.scss
  src/components/BlogComponents/Pagination/index.tsx
  src/components/BlogComponents/Pagination/util/generatePageList.ts
  src/components/BlogComponents/index.ts
  src/styles/templates/blog.module.scss
  src/styles/tokens.scss
  src/templates/blog.tsx
  src/types/markdown.ts
  src/types/pages/blog.ts
  src/types/pagination.ts
  util-node/__tests__/getPaginationPath.test.ts
  util-node/getPaginationPath.js
Labels: hacktoberfest-accepted

#2941 feat(docs): prepare for v19 and multiple doc support
  .nvmrc
  cloudbuild-deploy.yaml
  firebase.json
  gatsby-config.js
  gatsby-node.js
  package-lock.json
  package.json
  scripts/syncApiDocs.js
  src/hooks/useUpdateDocumentColorScheme.ts
  util-node/createApiPages.js
  util-node/getApiDocsData.js
  util-node/getBannersData.js
  util-node/getCurrentActiveReleases.js
  util-node/getNodeReleasesData.js
  util-node/getNvmData.js
Labels: docs, Infrastructure

#2953 fix(header): added a css fix for disallowing wrapping of whitespaces
  src/sections/Header/index.module.scss
Labels: fast track

#2958 fix(banners): fixed small banner alignment issue
  src/components/CommonComponents/Banner/index.module.scss
  src/util/__tests__/__snapshots__/getUpcomingReleases.test.ts.snap
  src/util/__tests__/getUpcomingReleases.test.ts
  util-node/__tests__/__snapshots__/getNodeReleasesData.test.ts.snap
Labels: fast track

#2961 fix: fix SearchBar for click event of close icon
  src/components/CommonComponents/SearchBar/index.tsx
Labels: hacktoberfest-accepted
