Repository nodejs/nodejs.dev, pull requests merged in 2022-09, with the labels that each got.

#2713 fix(design): some small design fixes
  src/components/Article/index.module.scss
  src/components/Header/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Header/index.tsx
  src/components/Layout/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Layout/__tests__/__snapshots__/page.test.tsx.snap
  src/components/TableOfContents/index.module.scss
  src/components/TableOfContents/index.tsx
  src/pages/download/__tests__/__snapshots__/index.test.tsx.snap
  src/pages/download/__tests__/__snapshots__/package-manager.test.tsx.snap
  src/pages/resources/__tests__/__snapshots__/index.test.tsx.snap
  src/templates/__tests__/__snapshots__/blog.test.tsx.snap
  src/templates/__tests__/__snapshots__/learn.test.tsx.snap
  src/templates/api.tsx
  util-node/apiDocsTransformUtils.js
Labels: bug, enhancement

#2727 fix(content): numerous content and design issues
  src/components/Article/index.module.scss
  src/components/Header/index.module.scss
  src/components/Hero/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Hero/index.module.scss
  src/components/Hero/index.tsx
  src/components/NavigationSection/index.module.scss
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/pages/__tests__/__snapshots__/index.test.tsx.snap
  src/styles/containers.scss
Labels: bug, enhancement

#2734 feat(releases): refactored how we display, parse and render release data
  content/api/v18/navigation.json
  gatsby-config.js
  gatsby-node.js
  package-lock.json
  package.json
  src/__fixtures__/page.tsx
  src/components/ApiComponents/Components/VersionSelector/index.module.scss
  src/components/ApiComponents/Components/VersionSelector/index.tsx
  src/components/Article/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Article/index.tsx
  src/components/DownloadAdditional/__tests__/index.test.tsx
  src/components/DownloadAdditional/index.tsx
  src/components/DownloadCards/index.tsx
  src/components/DownloadHeader/__tests__/__snapshots__/index.test.tsx.snap
  src/components/DownloadHeader/__tests__/index.test.tsx
  src/components/DownloadHeader/index.tsx
  src/components/DownloadReleases/DownloadTable/__tests__/__snapshots__/index.test.tsx.snap
  src/components/DownloadReleases/DownloadTable/__tests__/index.test.tsx
  src/components/DownloadReleases/DownloadTable/index.module.scss
  src/components/DownloadReleases/DownloadTable/index.tsx
  src/components/DownloadReleases/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Hero/__tests__/__snapshots__/index.test.tsx.snap
  src/components/Hero/__tests__/index.test.tsx
  src/components/Hero/index.tsx
  src/components/Layout/article.tsx
  src/components/NavigationSection/index.module.scss
  src/components/SearchBar/__tests__/SearchBar.test.tsx
  src/components/SearchBar/__tests__/__snapshots__/SearchBar.test.tsx.snap
  src/components/SideNavBar/index.module.scss
  src/components/UpcomingReleases/__tests__/__snapshots__/index.test.tsx.snap
  src/components/connectGraphQlArticle.tsx
  src/i18n/locales/en.json
  src/i18n/locales/es.json
  src/pages/__tests__/__snapshots__/index.test.tsx.snap
  src/pages/__tests__/index.test.tsx
  src/pages/about/__tests__/__snapshots__/releases.test.tsx.snap
  src/pages/about/releases.tsx
  src/pages/download/__tests__/__snapshots__/index.test.tsx.snap
  src/pages/download/__tests__/index.test.tsx
  src/pages/download/index.tsx
  src/pages/index.tsx
  src/templates/api.tsx
  src/types/index.ts
  src/util/getUpcomingReleases.ts
  test/__mocks__/@pkgjs/nv.js
  test/__mocks__/async.js
  util-node/__tests__/__snapshots__/getNodeReleasesData.test.ts.snap
  util-node/__tests__/getNodeReleasesData.test.ts
  util-node/createApiPages.js
  util-node/createApiQuery.js
  util-node/getApiDocsData.js
  util-node/getCurrentActiveReleases.js
  util-node/getNodeReleasesData.js
  util-node/getReleaseStatus.js
Labels: bug, docs

#2739 fix(css): minified html and include css on load
  gatsby-browser.tsx
  gatsby-config.js
  package-lock.json
  package.json
  src/components/Layout/index.tsx
Labels: bug

#2748 refactor(gatsby): optimized queries, types and imports
  firebase.json
  gatsby-config.js
  gatsby-node.js
  package-lock.json
  package.json
  scripts/generateRedirects.js
  src/__fixtures__/page.tsx
  src/components/ApiComponents/Components/index.tsx
  src/components/RecentPosts/__tests__/index.test.tsx
  src/components/SideNavBar/__tests__/__snapshots__/index.test.tsx.snap
  src/components/SideNavBar/__tests__/index.test.tsx
  src/components/SideNavBar/index.tsx
  src/components/connectGraphQlArticle.tsx
  src/containers/BlogContainer/index.tsx
  src/pages/__tests__/__snapshots__/blog.test.tsx.snap
  src/pages/__tests__/__snapshots__/community.test.tsx.snap
  src/pages/__tests__/blog.test.tsx
  src/pages/about/__tests__/__snapshots__/governance.test.tsx.snap
  src/pages/about/__tests__/__snapshots__/index.test.tsx.snap
  src/pages/about/__tests__/__snapshots__/privacy.test.tsx.snap
  src/pages/about/__tests__/__snapshots__/releases.test.tsx.snap
  src/pages/about/__tests__/__snapshots__/resources.test.tsx.snap
  src/pages/about/__tests__/__snapshots__/security.test.tsx.snap
  src/pages/about/__tests__/__snapshots__/working-groups.test.tsx.snap
  src/pages/about/__tests__/resources.test.tsx
  src/pages/about/resources.tsx
  src/pages/blog.tsx
  src/pages/download/__tests__/__snapshots__/package-manager.test.tsx.snap
  src/styles/templates/api.module.scss
  src/styles/templates/post.module.scss
  src/templates/__tests__/__snapshots__/post.test.tsx.snap
  src/templates/__tests__/post.test.tsx
  src/templates/api.tsx
  src/templates/blog-category.tsx
  src/templates/blog.tsx
  src/templates/learn.tsx
  src/templates/post.tsx
  src/types/api.ts
  src/types/article.ts
  src/types/banners.ts
  src/types/blog.ts
  src/types/index.ts
  src/types/markdown.ts
  src/types/navigation.ts
  src/types/pages/api.ts
  src/types/pages/blog.ts
  src/types/pages/index.ts
  src/types/pages/learn.ts
  src/types/pages/post.ts
  src/types/releases.ts
  util-node/createApiPages.js
  util-node/createApiQuery.js
  util-node/createBlogPages.js
  util-node/createBlogQuery.js
  util-node/createLearnPages.js
  util-node/createLearnQuery.js
  util-node/createPageUtils.js
  util-node/createPagesQuery.js
  util-node/generateRedirects.js
Labels: enhancement, Infrastructure

#2750 feat(workflows): updated github actions workflows
  .github/workflows/cleanup-staging.yml
  .github/workflows/gatsby.yml
  .github/workflows/generate-preview.yml
  .github/workflows/github-pages.yml
  .github/workflows/pull-request.yml
  .github/workflows/test.yml
Labels: Infrastructure

#2752 fix(workflow): fixed workflow name
  .github/workflows/github-pages.yml
Labels: bug

#2767 test: Add a11y tests to pages
  src/pages/__tests__/__snapshots__/index.test.tsx.snap
  src/pages/__tests__/index.test.tsx
  src/pages/__tests__/style-guide.test.tsx
  src/pages/about/__tests__/releases.test.tsx
  src/pages/about/__tests__/resources.test.tsx
  src/pages/about/__tests__/security.test.tsx
  src/pages/get-involved/__tests__/code-learn.test.tsx
  src/pages/get-involved/__tests__/collab-summit.test.tsx
  src/pages/get-involved/__tests__/contribute.test.tsx
  src/pages/get-involved/__tests__/index.test.tsx
  src/pages/index.tsx
  src/styles/typography.scss
Labels: a11y

#2800 fix(learn): fixes links to use path prefix calculation
  content/learn/command-line/node-cli-args.en.md
  content/learn/getting-started/node-installation.en.md
  util-node/createLearnQuery.js
  util-node/createPageUtils.js
Labels: bug, blog
