Repository nodejs/nodejs.dev, pull requests merged in 2022-11, with the labels that each got.

#2959 chore(node): be strict about engine version
  package-lock.json
  package.json
Labels: Infrastructure

#3021 hotfix(language-detection): fix language detection
  package-lock.json
  src/hooks/__tests__/useFeatureToggles.test.tsx
  src/hooks/useBrowserLanguageDetection.ts
  src/hooks/useStorage.ts
  src/layouts/default.tsx
  src/providers/FeatureToggles/index.tsx
Labels: i18n, fast track

#3028 hotfix(json): introduced a safe json parser
  gatsby-node.js
  src/components/ArticleComponents/EditLink/__tests__/__snapshots__/edit-link.test.tsx.snap
  src/hooks/useStorage.ts
  src/layouts/__tests__/__snapshots__/page.test.tsx.snap
  src/pages/about/__tests__/__snapshots__/governance.test.tsx.snap
  src/pages/about/__tests__/__snapshots__/index.test.tsx.snap
  src/pages/about/__tests__/__snapshots__/releases.test.tsx.snap
  src/pages/about/__tests__/__snapshots__/resources.test.tsx.snap
  src/pages/about/__tests__/__snapshots__/security.test.tsx.snap
  src/pages/download/__tests__/__snapshots__/package-manager.test.tsx.snap
  src/sections/Article/__tests__/__snapshots__/index.test.tsx.snap
  src/templates/__tests__/__snapshots__/learn.test.tsx.snap
  util-node/apiDocsTransformUtils.js
  util-node/createApiPages.js
  util-node/generateRedirects.js
  util-node/getApiDocsData.js
  util-node/safeJSON.js
Labels: fast track

#3045 fix(absolute-url): fix absolute url util
  src/util/isAbsoluteUrl.ts
Labels: fast track

#3047 fix: Add missing banner image (#3044)
  static/static/images/nodejs-training.png
Labels: Infrastructure, fast track
