Repository nodejs/nodejs.dev, pull requests merged in 2022-08, with the labels that each got.

#2610 chore(dependencies): switched to safest newest dependencies
  .eslintrc.js
  .storybook/addons.js
  .storybook/main.js
  .storybook/preview.js
  gatsby-config.js
  package-lock.json
  package.json
  src/components/Article/__tests__/__snapshots__/article.test.tsx.snap
  src/components/BlogAuthorsList/__tests__/__snapshots__/blog-author.test.tsx.snap
  src/components/BlogCard/__tests__/__snapshots__/blog-card.test.tsx.snap
  src/components/DownloadCards/__tests__/__snapshots__/download-cards.test.tsx.snap
  src/components/DownloadReleases/__tests__/__snapshots__/download-releases.test.tsx.snap
  src/components/Header/__tests__/__snapshots__/header.test.tsx.snap
  src/components/Header/__tests__/header.test.tsx
  src/components/Header/index.tsx
  src/components/InstallTabs/__tests__/__snapshots__/index.tsx.snap
  src/components/Layout/__tests__/__snapshots__/centered-layout.test.tsx.snap
  src/components/Layout/__tests__/__snapshots__/layout.test.tsx.snap
  src/components/Layout/__tests__/__snapshots__/page-layout.test.tsx.snap
  src/components/UpcomingReleases/__tests__/__snapshots__/upcoming-releases.test.tsx.snap
  src/types/gatsby-plugin-dark-mode.d.ts
  test/pages/__snapshots__/404.test.tsx.snap
  test/pages/__snapshots__/about.test.tsx.snap
  test/pages/__snapshots__/blog.test.tsx.snap
  test/pages/__snapshots__/community.test.tsx.snap
  test/pages/__snapshots__/governance.test.tsx.snap
  test/pages/__snapshots__/home.test.tsx.snap
  test/pages/__snapshots__/privacy.test.tsx.snap
  test/pages/__snapshots__/releases.test.tsx.snap
  test/pages/__snapshots__/resources.test.tsx.snap
  test/pages/__snapshots__/security.test.tsx.snap
  test/pages/__snapshots__/trademark.test.tsx.snap
  test/pages/__snapshots__/working-groups.test.tsx.snap
  test/pages/download/__snapshots__/index.test.tsx.snap
  test/pages/download/__snapshots__/package-manager.test.tsx.snap
  test/templates/__snapshots__/blog.test.tsx.snap
  test/templates/__snapshots__/learn.test.tsx.snap
Labels: enhancement, dependencies

#2608 feat(feature-toggle): introduced feature toggle manager
  src/components/FeatureToggleProvider.tsx
  src/components/Layout/index.tsx
  src/hooks/index.tsx
  src/hooks/useFeatureToggles.ts
  test/components/SideNavBar.test.tsx
  test/components/aboutPageSideNavBar.test.tsx
  test/hooks/__snapshots__/useFeatureToggles.test.tsx.snap
  test/hooks/useFeatureToggles.test.tsx
  test/pages/home.test.tsx
Labels: i18n

#2657 Fix/broken links in learn quick start
  content/learn/node-javascript-language.en.md
  content/learn/node-module-path.en.md
  content/learn/package-json.en.md
  src/data/learn.yaml
  util-node/createMarkdownPages.js
Labels: bug, good first issue, docs

#2665 fix(search-bar): fixed search bar styling and made it exclusive to search-bar
  src/components/Header/__tests__/__snapshots__/header.test.tsx.snap
  src/components/Header/index.tsx
  src/components/Layout/__tests__/__snapshots__/centered-layout.test.tsx.snap
  src/components/Layout/__tests__/__snapshots__/layout.test.tsx.snap
  src/components/Layout/__tests__/__snapshots__/page-layout.test.tsx.snap
  src/styles/layout.scss
  src/styles/mobile.scss
  test/pages/__snapshots__/404.test.tsx.snap
  test/pages/__snapshots__/about.test.tsx.snap
  test/pages/__snapshots__/blog.test.tsx.snap
  test/pages/__snapshots__/community.test.tsx.snap
  test/pages/__snapshots__/governance.test.tsx.snap
  test/pages/__snapshots__/home.test.tsx.snap
  test/pages/__snapshots__/privacy.test.tsx.snap
  test/pages/__snapshots__/releases.test.tsx.snap
  test/pages/__snapshots__/resources.test.tsx.snap
  test/pages/__snapshots__/security.test.tsx.snap
  test/pages/__snapshots__/trademark.test.tsx.snap
  test/pages/__snapshots__/working-groups.test.tsx.snap
  test/pages/download/__snapshots__/index.test.tsx.snap
  test/pages/download/__snapshots__/package-manager.test.tsx.snap
  test/templates/__snapshots__/blog.test.tsx.snap
  test/templates/__snapshots__/learn.test.tsx.snap
Labels: bug
